env: 
  global: 
    - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - LD_LIBRARY_PATH=/home/travis/build/casadi/casadi/libhsl
    - secure: KvMG4VORV7Ja09shvmsMpiaRMoWqupR76dKxOd7W28I//F4YDIn5ZZefM4aoXsmRgs4G9YqloU8JjVpHutZARmKn2drUwHVMA+96iKb9eDODwZaKXgFYsrQIX5c/OgO8ZpsXynD2daqH3bMK8Mjz1+4fjbFToPFXHggxqQuHm1U=
    - CMAKE_INCLUDE_PATH=/home/travis/build/casadi/casadi/testbot/restricted/cplex/cplex/include:/home/travis/build/casadi/casadi/testbot/restricted/cplex/concert/include
    - CMAKE_LIBRARY_PATH=/home/travis/build/casadi/casadi/testbot/restricted/cplex/cplex/lib/x86-64_sles10_4.1/static_pic/:/home/travis/build/casadi/casadi/testbot/restricted/cplex/concert/lib/x86-64_sles10_4.1/static_pic/
    - ILOG_LICENSE_FILE=/home/travis/build/casadi/casadi/testbot/restricted/cplex/access.ilm
    - WORHP=/home/travis/build/casadi/casadi/testbot/restricted/worhp
    - SNOPT=/home/travis/build/casadi/casadi/snopt7
    - PYTHONPATH=/home/travis/build/casadi/casadi/install
compiler: 
- gcc
- clang
before_install:
- sudo ifconfig
- git clone https://github.com/casadi/testbot.git
- pushd testbot && recipes/setup.sh && popd
- sudo apt-get install p7zip-full -y
- testbot/recipes/fetch.sh libhsl.tar.gz && mkdir libhsl && tar -xvf libhsl.tar.gz -C libhsl
- testbot/recipes/fetch.sh snopt7.tar.gz && mkdir snopt7 && tar -xvf snopt7.tar.gz -C snopt7
- pushd testbot/restricted/cplex && mkdir cplex && tar -xvf cplex12.4.tar.gz -C cplex && mkdir concert && tar -xvf cplex12.4-concert.tar.gz -C concert && popd
- pushd testbot/restricted && mkdir worhp && cd  worhp && 7za e ../libworhp_debian7_amd64_gcc47_1.6-3.7z && popd
- ldd /home/travis/build/casadi/casadi/testbot/restricted/worhp/libworhp.so
- sudo add-apt-repository ppa:umn-claoit-rce/compute-packages -y
- sudo apt-get update -qq
- sudo apt-get install -y binutils gcc g++ gfortran git cmake liblapack-dev swig ipython python-dev python-numpy python-scipy python-matplotlib coinor-libipopt-dev libmumps-seq-dev libblas-dev liblapack-dev libslicot-dev libxml2-dev
install: 
- mkdir build
- cd build
- cmake -DWITH_WORHP=ON   -DWITH_SLICOT=ON -D PYTHON_PREFIX=/home/travis/build/casadi/casadi/install -D CMAKE_INSTALL_PREFIX=/home/travis/build/casadi/casadi/install ..
- make VERBOSE=TRUE
- ldd lib/libcasadi_nlpsolver_worhp.so
- readelf -d lib/libcasadi_nlpsolver_worhp.so
- make python
- sudo make install install_python
- ldd /usr/local/lib/casadi/libcasadi_nlpsolver_worhp.so
- readelf -d /home/travis/build/casadi/casadi/install/lib/casadi/libcasadi_nlpsolver_worhp.so
python: 
- 2.7_with_system_site_packages
script: 
- cd ../test
- python -c "from casadi.tools import *;loadAllCompiledPlugins()"
- make unittests_py examples_code_py
os: 
- linux
- osx
language: cpp
