language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
python:
  - "2.7_with_system_site_packages"
before_install:
  - cat /home/travis/.ssh/id_rsa.pub
  - ssh -vT git@github.com
  - git clone git@github.com:jgillis/restricted.git
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc g++ gfortran git cmake liblapack-dev swig ipython python-dev python-numpy python-scipy python-matplotlib
install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install


script:
  - cd ../test
  - make unittests_py examples_code_py
