env: 
  global: 
    - IPOPT_DEFAULT_LINEAR_SOLVER=ma57
    - LD_LIBRARY_PATH=/home/travis/build/casadi/casadi/libhsl
    - secure: KvMG4VORV7Ja09shvmsMpiaRMoWqupR76dKxOd7W28I//F4YDIn5ZZefM4aoXsmRgs4G9YqloU8JjVpHutZARmKn2drUwHVMA+96iKb9eDODwZaKXgFYsrQIX5c/OgO8ZpsXynD2daqH3bMK8Mjz1+4fjbFToPFXHggxqQuHm1U=
    - CMAKE_INCLUDE_PATH=/home/travis/build/casadi/casadi/restricted/cplex/cplex/include:/home/travis/build/casadi/casadi/restricted/cplex/concert/include
    - CMAKE_LIBRARY_PATH=/home/travis/build/casadi/casadi/restricted/cplex/cplex/lib/x86-64_sles10_4.1/static_pic/:/home/travis/build/casadi/casadi/restricted/cplex/concert/lib/x86-64_sles10_4.1/static_pic/
    - ILOG_LICENSE_FILE=/home/travis/build/casadi/casadi/restricted/cplex/access.ilm
compiler: 
- gcc
- clang
before_install:
- git clone https://github.com/casadi/testbot.git
- pushd testbot && recipes/setup.sh && popd
- testbot/recipes/fetch.sh libhsl.tar.gz && mkdir libhsl && tar -xvf libhsl.tar.gz -C libhsl
- pushd restricted/cplex && mkdir cplex && tar -xvf cplex/cplex12.4.tar.gz -C cplex && mkdir concert && tar -xvf cplex/cplex12.4-concert.tar.gz -C concert && popd
- sudo apt-get update -qq
- sudo apt-get install -y gcc g++ gfortran git cmake liblapack-dev swig ipython python-dev python-numpy python-scipy python-matplotlib coinor-libipopt-dev libmumps-seq-dev libblas-dev liblapack-dev
install: 
- mkdir build
- cd build
- cmake ..
- make
- sudo make install
python: 
- 2.7_with_system_site_packages
script: 
- cd ../test
- python -c "from casadi.tools import *;loadAllCompiledPlugins()"
- make unittests_py examples_code_py
os: 
- linux
- osx
language: cpp
