environment:
 matrix: 
    - TESTMODE: win_vs
    - TESTMODE: win_msys
install:
  - git clone https://github.com/casadi/testbot.git
  
build_script:
- set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
- testbot/testmodes/%TESTMODE%.bat
